name: Build Cog
description: Compile Cog from source using a specified commitish.
author: replicate
branding:
  icon: settings
  color: gray-dark

inputs:
  commitish:
    description: "The commitish (branch, tag, or commit) of Cog to build from source"
    required: false
    default: 'main'

runs:
  using: "composite"
  steps:
  - name: Checkout Cog repository
    uses: actions/checkout@v4
    with:
      repository: 'replicate/cog'
      fetch-depth: 0
      path: 'cog-repo'

  - name: Install Go
    uses: actions/setup-go@v5
    with:
      go-version-file: 'cog-repo/go.mod'

  - name: Build Cog
    shell: bash
    run: cd cog-repo && make cog

  - name: Add Cog to PATH
    shell: bash
    run: echo "${{ github.workspace }}/cog-repo" >> $GITHUB_PATH

